### ISSUE TITLE
Add heading numbering to Antora output

### ISSUE THREAD

**Issue by nakohdo** [asam-ev/OpenMATERIAL#66]
## Problem
The [Antora output of OpenMATERIAL](https://asam-ev.github.io/OpenMATERIAL) does not contain numbered headings as other ASAM documentation, for example, [ASAM OSI](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/specification/index.html). This problem has been reported in #54. 

## Cause
The current, basic Antora configuration does not contain the setting for heading numbering yet. These settings are part of the [ASAM Antora Extensions](https://common.pages.asam.net/antora-ui/ASAM_Antora_Extensions/antora/consistent_numbering/description.html).

## Solution 
Add the configuration to the Antora playbook file. 

```YAML
antora:
  extensions:
  - require: './asam-antora-extensions/asam-antora_extension.js'
    numbered_titles: true
    section_number_style: "iso"
```
